// <auto-generated />
using System;
using BrowserProfileLauncher.Core.EntityFramework.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrowserProfileLauncher.Core.EntityFramework.Migrations.BrowserProfileLauncher
{
    [DbContext(typeof(BrowserProfileLauncherDbContext))]
    [Migration("20210418160910_InitializeDatabase")]
    partial class InitializeDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrowserProfileLauncher.Core.EntityFramework.Entities.BrowserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProxyIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProxyPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProxyPort")
                        .HasColumnType("int");

                    b.Property<string>("ProxyProtocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProxyUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BrowserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
