// <auto-generated />
using System;
using BrowserProfileLauncher.Core.EntityFramework.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrowserProfileLauncher.Core.EntityFramework.Migrations.BrowserProfileLauncher
{
    [DbContext(typeof(BrowserProfileLauncherDbContext))]
    [Migration("20210421144529_AddProfileGroupTable")]
    partial class AddProfileGroupTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrowserProfileLauncher.Core.EntityFramework.Entities.BrowserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProxyIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProxyPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProxyPort")
                        .HasColumnType("int");

                    b.Property<string>("ProxyProtocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProxyUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("BrowserProfiles");
                });

            modelBuilder.Entity("BrowserProfileLauncher.Core.EntityFramework.Entities.ProfileGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProfileGroups");
                });

            modelBuilder.Entity("BrowserProfileLauncher.Core.EntityFramework.Entities.BrowserProfile", b =>
                {
                    b.HasOne("BrowserProfileLauncher.Core.EntityFramework.Entities.ProfileGroup", "Group")
                        .WithMany("BrowserProfiles")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BrowserProfileLauncher.Core.EntityFramework.Entities.ProfileGroup", b =>
                {
                    b.Navigation("BrowserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
